---
output:
  html_document: default
  pdf_document: default
---
Course Project 1 - Reproducible Research
========================================


```{r, echo=TRUE}                     
# Loading and preprocessing the data
path = getwd()
unzip("repdata_data_activity.zip", exdir = path)
act <- read.csv("activity.csv")
head(act)
summary(act)
```

### What is mean total number of steps taken per day?
```{r, echo=TRUE}  
#1. Calculate the total number of steps taken per day
TotalSteps<-aggregate(steps~date, act, sum)

#2. Make a histogram of the total number of steps taken each day
hist(TotalSteps$steps, col = "cyan", xlab="Total Number of Steps Per Day", ylab="Number of Days", main="Total Number of Steps Taken on a Day")

#3. Calculate and report the mean and median of the total number of steps taken per day
TotalMean <-mean(TotalSteps$steps)
TotalMean
TotalMedian<-median(TotalSteps$steps)
TotalMedian

```

### What is the average daily activity pattern?
```{r, echo=TRUE} 
# 1. Make a time series plot of the 5-minute interval (x-axis) and the average number of steps taken, averaged across all days (y-axis)
#Average Steps Taken
AveStepsInterval<-aggregate(steps~interval, act, mean)
with(AveStepsInterval, plot(interval, steps, type = "l"))

#2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?
AveStepsInterval[which.max(AveStepsInterval[,2]),1]

```

### Imputing missing values

